#!/usr/bin/env python3

import boto3
import random

AWS_REGION = 'us-east-1'

client = boto3.client( 'logs' , region_name = AWS_REGION )

#client = boto3.client( 's3' )

response = client.get_log_events(
        logGroupName= '/var/log/messages',
        logStreamName= 'i-0d7d2ca5c1c3d75f8',
        limit= 123,
        startFromHead= True 
                           )

log_events = response['events']
logfile=open("myfile.txt" , "w")
logfile.close()

for each_event in log_events:
    logfile =open("myfile.txt" , "a") 
    x = each_event 
    logfile.write(str(x))
    logfile.write('\n')
    logfile.close()


client =boto3.client( 's3')

def upload_files( file_name, bucket, objectname, args = None):
  response= client.upload_file(file_name, bucket, objectname, ExtraArgs= args)
  #print(response)

upload_files('myfile.txt','voistask',objectname= 'ec2-logs/')
